<div class="rcct_detail">
								<div class="tn_title">Nhiệm vụ Lôi Thần Điện</div>
								<div class="tn_time">Cập nhật lúc 23-09-2014 15:14:39</div>
								<div class="rdt_post"><span style="font-size: medium;"><span style="font-family: 'Times New Roman';">&nbsp;<strong style="font-size: larger; color: rgb(123, 155, 153); font-family: Tahoma, Geneva, sans-serif; text-align: center; border: 0px; margin: 0px; padding: 0px; vertical-align: baseline; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;">HỆ&nbsp;THỐNG&nbsp;NHIỆM&nbsp;VỤ&nbsp;MỚI</strong><br>
<br style="color: rgb(123, 155, 153); font-family: Tahoma, Geneva, sans-serif;">
</span></span>
<div style="border: 0px; margin: 0px; padding: 0px; vertical-align: baseline; color: rgb(123, 155, 153); font-family: Tahoma, Geneva, sans-serif; text-align: justify; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><span style="font-size: medium;"><span style="font-family: 'Times New Roman';"><span style="border: 0px; margin: 0px; padding: 0px; vertical-align: baseline; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;">Trong đợt cập nhật phiên bản Bí ẩn Lôi Thần Điện tới đây, Con Đường Tơ Lụa sẽ cập nhật thêm 120 nhiệm vụ lớn nhỏ khác nhau liên quan tới Lôi Thần Điện và các vị thần. Với hệ thống nhiệm vụ đồ sộ và hấp dẫn, Con Đường Tơ Lụa sẽ giúp cho người chơi không những nhanh chóng thăng cấp độ nhân vật mà còn như được sống trong những câu chuyện thần thoại của người dân La Mã. Dưới đây là danh sách chi tiết các nhiệm vụ trong phiên bản này:<br>
<br>
<span style="border: 0px; margin: 0px; padding: 0px; vertical-align: baseline; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><strong style="border: 0px; margin: 0px; padding: 0px; vertical-align: baseline; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;">Lưu ý: Người chơi có thể click vào hình ảnh để xem chi tiết bảng nhiệm vụ này một cách rõ nhất</strong></span><br>
<br>
</span></span></span></div>
<div style="border: 0px; margin: 0px; padding: 0px; vertical-align: baseline; color: rgb(123, 155, 153); font-family: Tahoma, Geneva, sans-serif; text-align: center; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><a href="http://image.ongame.vn/images/file/bangnhiemvu_LoiThanDien.png" target="_blank" style="border: 0px; margin: 0px; padding: 0px; vertical-align: baseline; text-decoration: none; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><span style="font-size: medium;"><span style="font-family: 'Times New Roman';"><img width="700" src="http://image.ongame.vn/images/file/bangnhiemvu_LoiThanDien.png" alt="" style="border: none; margin: 0px; padding: 0px; vertical-align: baseline; opacity: 0.8; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"></span></span></a></div>
<div>&nbsp;</div></div>
							</div>